sudo: required
dist: xenial
language: node_js
node_js:
  - '16.15.1'
services:
  - xvfb
addons:
    chrome: stable
before_script:
- npm cache verify
- npm run lint
- npm run build:app
- npm run build:lib

script: npm run test:lib
