// tslint:disable
export const ACCESS_TOKEN = 'TOKEN_HERE';
export const DOCUMENT_URN = 'dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6bmJzdmlld2VyL0E0ODdCREQwNTM1NjcxNzYxMTE2RTIyMzk0QTYxOEIwLnJ2dA';

export const MULTIPLE_MODEL_URNS = [
  'dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6dG9vbGtpdC9BMTY4MThBMDMxNTYyM0M5MEY2QUVGQkNENjdDRDRFQi5ydnQ',
  'dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6bmJzdmlld2VyL0I2QkM3NDVCRTUxRTkwMkUzQTY2NkE0NEFERDNCRERDLnJ2dA',
];
